### ISSUE TITLE
Support for graphiql

### ISSUE THREAD

**Issue by destroyer22719** [graphql/graphql-http#82] opened 2023-04-25 02:17 UTC
I was looking forward to starting to learn graphql and migrate from rest for my a personal project. Every other tutorial in the realm of NodeJS and Express recommend to use `express-graph` but it is deprecated and this module is recommend. However, I noticed one feature seems to be missing, `graphiql`. This isn't a dealbreaker but it would be nice to have this feature in `graphql-http`.

**Comment by raulfdm** [comment] 2023-04-25 07:14
+1

**Comment by enisdenjo** [comment] 2023-04-25 12:55
Duplicate of #38.

**Closed by enisdenjo** 2023-04-25 12:55 UTC
