### ISSUE TITLE
Add graphiql in createHandler method

### ISSUE THREAD

**Issue by AmirHosein-Zare** [graphql/graphql-http#72] opened 2023-04-03 11:37 UTC
### Story

As a _user or client or server_

I want _some feature_

So that _some value_

### Acceptance criteria

- _user or client or server type_ is able to...
- _user or client or server type_ can add...
- _user or client or server type_ can remove...

**Comment by enisdenjo** [comment] 2023-04-03 11:59
Duplicate of #38, please read https://github.com/graphql/graphql-http/discussions/38#discussioncomment-4698804.

**Closed by enisdenjo** 2023-04-03 11:59 UTC

**Comment by gpbaculio** [comment] 2023-09-29 19:06
using Postman for something like this:

 `const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: "Query",
    fields: {
      hello: {
        type: GraphQLString,
        resolve: () => "world",
      },
    },
  }),
});`

do this:

![Screenshot 2023-09-30 at 3 06 06 AM](https://github.com/graphql/graphql-http/assets/17801912/1b63cbb9-f512-4164-9a59-4518361614a4)
